os: linux
dist: bionic
language: php

php:
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  - |
    if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then
      travis_retry travis_retry make vendor EXTRA_FLAGS="--ignore-platform-reqs";
    else
      travis_retry travis_retry make vendor;
    fi

script:
  - make unit-test

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Code Quality
      env: TEST_COVERAGE=1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - make unit-test EXTRA_FLAGS="--coverage-clover ./clover.xml"
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

    - stage: Code Quality
      env: CODE_STANDARD=1
      script:
        - make coding-standard

    - stage: Code Quality
      env: STATIC_ANALYSIS=1
      script:
        - make static-analysis

    - stage: Code Quality
      env: MUTATION_TESTS=1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for mutation tests"; exit 1; fi
      script:
        - make mutation-test
